version: '2'
services:

  pdiapi-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./pdiapi-service/target:/app
      - ./scripts:/scripts
      - ./newrelic:/newrelic
    command: /scripts/run-spring-boot.sh 128 pdiapi-service.jar nr-pdiapi-service.yml
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-service:8080
      SPRING_PROFILES_ACTIVE: docker-compose
      NEW_RELIC_LICENSE_KEY: ${NRLK}
    ports:
      - "8080"
    labels:
        - "interlock.hostname=pdiapi-service"
        - "interlock.domain=streamline"

  pdicrawler-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./pdicrawler-service/target:/app
      - ./scripts:/scripts
      - ./newrelic:/newrelic
    command: /scripts/run-spring-boot.sh 128 pdicrawler-service.jar nr-pdicrawler-service.yml
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-service:8080
      SPRING_PROFILES_ACTIVE: docker-compose
      NEW_RELIC_LICENSE_KEY: ${NRLK}
      STREAMLINE_GOOGLE_API_AUTH: ${STREAMLINE_GOOGLE_API_AUTH}
    ports:
      - "8080"
    labels:
        - "interlock.hostname=pdicrawler-service"
        - "interlock.domain=streamline"
      
  pdiondemand-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./pdiondemand-service/target:/app
      - ./scripts:/scripts
      - ./newrelic:/newrelic
    command: /scripts/run-spring-boot.sh 128 pdiondemand-service.jar nr-pdiondemand-service.yml
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-service:8080
      SPRING_PROFILES_ACTIVE: docker-compose
      NEW_RELIC_LICENSE_KEY: ${NRLK}
    ports:
      - "8080"
    labels:
      - "interlock.hostname=pdiondemand-service"
      - "interlock.domain=streamline"

